package model;

public interface Acao {
	int ATUALIZACAO_ESTADO = 1;
	int REQUISICAO_ANIVERSARIO = 2;
	int RESPOSTA_PARA_O_ANIVERSARIANTE = 3;
	int ATUALIZAR_SORTE_GRANDE = 4;
	int INICIO_MARATONA_BENEFICENTE = 5;
	int FIM_MARATONA_BENEFICENTE = 6;
	int PAGUEI_VIZINHO = 7;
	int INICIO_JOGADA = 8;
	int PROXIMO_JOGADOR = 9;
	int FIM_DE_MES = 10;
	int DINHEIRO_EXTRA = 11;
}
