package model;

public interface Acao {
	int ATUALIZACAO_ESTADO = 1;
	int REQUISICAO_ANIVERSARIO = 2;
	int RESPOSTA_PARA_O_ANIVERSARIANTE = 3;
	int ATUALIZAR_SORTE_GRANDE = 4;
	int INICIO_MARATONA_BENEFICENTE = 5;
	int FIM_MARATONA_BENEFICENTE = 6;
}
